#!/bin/sh
### BEGIN INIT INFO
# Provides:          autorename
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Autorename RPC Server
# Description:       Debian init script for Autorename RCP Server root monitoring daemon
### END INIT INFO
#
# Author:	Manuel Mora Gordillo <manuito at gmail.com>
#                                                                                                                                      

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

NAME=autorenameRPCServer
message="Autorename RPC Server daemon"

rundir=/var/run 
pidfile=$rundir/autorename/rpcServer.pid
logfile=/var/log/autorename-server.log
daemon="/usr/bin/python"
application=/usr/share/autorename-server/server.py

test -x $DAEMON || exit 0
test -r $application || exit 0
rm -rf /tmp/autorename*

. /lib/lsb/init-functions

if [ ! -d /var/run/autorename ]; then
	rm -rf /var/run/autorename
	mkdir -p /var/run/autorename
fi

case "$1" in
    start)
		log_daemon_msg "Starting $message"
		[ ! -f $logfile ] && touch $logfile
		start-stop-daemon --start --quiet --pidfile=$pidfile --make-pidfile --exec $daemon $application &
		log_end_msg 0
		;;
	
    stop)
		log_daemon_msg "Stopping $message"
		start-stop-daemon --stop --quiet --pidfile $pidfile
		rm -rf /tmp/autorename*
		log_end_msg 0
		;;
	
    reload)
    	log_daemon_msg "Reloading $message"
		start-stop-daemon --stop --quiet --signal HUP --pidfile $pidfile &
    	log_end_msg 0
    	;;
    	
    restart|force-reload)
		log_daemon_msg "Restarting $message"
		$0 stop
		sleep 1
		$0 start
		log_end_msg 0
		;;
	*)
		log_success_msg "Usage: $0 {start|stop|restart|force-reload|reload}"
		exit 1
		;;
esac

exit 0
